language: node_js

node_js:
  - "lts/dubnium"

install:
  - npm ci

script:
  - npm run lint

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: "dist"
  on:
    branch: master
    tags: true